freebsd_instance:
  image_family: freebsd-12-1

task:
  env:
    GHRELEASER_VERSION: v0.13.0
    BASH_CMD: /usr/local/bin/bash
  install_script:
    - echo $SHELL
    - pwd
    - pkg install -y curl git go bash
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
    - set PATH=$HOME/.cago/bin:$PATH || true
  install_ghr_script: .cirrusci/install_ghr.sh
  build_script: .cirrusci/build.sh || true
  deploy_script: .cirrusci/deploy.sh || true
