[package]
name = "unix_stream"
version = "0.1.0"
authors = ["Hamid Ghadyani <hamid@hamid.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = { version = "0.3.10", features = ["unix", "reuseport", "pair"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = { version = "*", features = ["v4", "serde"] }
dirs = "2.0"
