[package]
name = "rmate"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = { version = "0.3", features = ["unix", "reuseport", "pair"] }
dirs = "2.0"
tempfile = "3"
base64 = "0.12"
rand = "0.7"
structopt = "0.3"

[profile.release]
lto = "fat"
